apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MTIzNA==
  POSTGRES_DB: Q2xpZW50
  POSTGRES_HOST: cG9zdGdyZXNzLXNlcnZpY2U=
  POSTGRES_PORT: NTQzMg==

