apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: postgres     
  POSTGRES_PASSWORD: 1234
  POSTGRES_DB: Client
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: 5432
